/*
 * @creater: panan
 * @message: mock.ts
 * @since: 2025-04-14 15:17:28
 * @LastAuthor: panan panan2001@outlook.com
 * @lastTime: 2025-04-14 15:27:18
 * @文件相对于项目的路径: /pan-umi/mock.ts
 */
export const mockData = {
  id: 20128,
  modelFolderId: 64,
  name: 'sft:qwen7b 2.5 补充越南附注表定位数据，新增3个库表数据业务',
  description: 'sft:qwen7b 2.5 补充越南附注表定位数据，新增3个库表数据业务',
  trainType: 2,
  executorType: 2,
  status: 'SUCCESS',
  clusterCode: 'csva2ai',
  resourcePool: 'nlp-sft-h100',
  resourcePoolAlias: 'nlp-sft-h100',
  deployModelId: null,
  creator: 'guoxinrun@myhexin.com',
  createTime: '2025-04-13 18:28:53',
  beginTime: '2025-04-13 21:37:51',
  endTime: '2025-04-14 06:20:57',
  creatorName: '郭鑫润',
  deployModelVersion: null,
  runTime: 31386000,
  sumResource: {
    sumNodeCount: 1,
    sumCpuCount: 20,
    sumMemoryCount: 500,
    sumGpuCount: 8,
  },
  modelFolderName: '数据部抽取大模型',
  existLabel: true,
  trainLabels: null,
  trainDatasets: null,
  commitUrl:
    'https://git-cc.myhexin.com:6443/10jqka/llm/aime-ai-llm/llm-nlu/-/commit/ee751803764ee2e9aded8f062e96231e939f98c2',
  spec: {
    trainId: 20128,
    image: 'alvahub.hexin.cn:9081/hithink-gallery/llm:241101',
    framework: 'PyTorchJob',
    command:
      'cd /data/code/llm-nlu\n\npip install json-repair -i https://pypi.tuna.tsinghua.edu.cn/simple\nbash run.sh /data/config/config.yaml  #上传report\n',
    priority: 7,
    gpuModel: 'H100',
    disableReclaim: false,
    trainStoragePathId: 60648,
    trainMountPath: '/mnt/workspace',
    trainEnvVar: '',
    errorMsg: null,
    codeInfo: {
      gitlabSource: 'git-cc',
      repository:
        'https://git-cc.myhexin.com:6443/10jqka/llm/aime-ai-llm/llm-nlu.git',
      branch: 'master',
      commitId: 'ee751803764ee2e9aded8f062e96231e939f98c2',
      commitUrl:
        'https://git-cc.myhexin.com:6443/10jqka/llm/aime-ai-llm/llm-nlu/-/commit/ee751803764ee2e9aded8f062e96231e939f98c2',
      storagePathId: 60649,
      mountPath: '/data/code',
      envVar: '',
      workflowInstanceId: '108444431537229827',
      additions: 4,
      deletions: 4,
      total: 8,
    },
    nodeInfo: [
      {
        nodeType: 'worker',
        nodeCount: 1,
        cpu: 20,
        memory: 500,
        gpuCount: 8,
        shareMemory: null,
      },
    ],
    baseModelInfo: {
      modelFolderId: 64,
      modelId: 2822,
      modelCopyId: 4599,
      mountPath: '/data/baseModel',
      envVar: '',
    },
    sampleInfo: [
      {
        sampleFolderId: 202,
        sampleId: 2456,
        sampleCopyId: 3859,
        mountPath: '/data/sample',
        envVar: '',
      },
      {
        sampleFolderId: 171,
        sampleId: 430,
        sampleCopyId: 1776,
        mountPath: '/sft/data',
        envVar: '',
      },
    ],
    orgSampleInfo: [
      {
        id: 708,
        trainId: 20128,
        orgKey: 'AIMELlm',
        orgInfo: {
          id: '67d24b686e3df54c5c7c3dc5',
          name: 'AIMELlm',
          desc: '<p>AIME语言大模型训练数据</p>',
          key: 'AIMELlm',
          path: '/datasetsGroup/AIMELlm',
        },
        storageId: 15,
        storageInfo: {
          id: 15,
          storageName: 'coresite-弗吉尼亚二-人工智能-ssd',
          description: 'coresite-弗吉尼亚二-人工智能-ssd',
          cluster: 'csva2ai',
          storageType: 0,
          transferStorageId: 23,
          storageRootPath: '/ai-cephfs',
          hostPath: '/mnt/ceph-fuse/hostpath-master',
          transferStorageName: 'coresite-弗吉尼亚二-人工智能-ssd',
          agentMountPath: '/mnt/ai-cephfs',
        },
        samplingType: 'num',
        samplingList: [
          {
            id: 6064,
            sampleId: 708,
            datasetId: 641,
            datasetVersionId: 5041,
            datasetVersion: 15,
            semanticVersion: '0.0.11',
            datasetName: '抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 2896,
            samplingValue: 2896,
          },
          {
            id: 6065,
            sampleId: 708,
            datasetId: 641,
            datasetVersionId: 5040,
            datasetVersion: 14,
            semanticVersion: '0.0.12',
            datasetName: '抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 24839,
            samplingValue: 24839,
          },
          {
            id: 6066,
            sampleId: 708,
            datasetId: 641,
            datasetVersionId: 5038,
            datasetVersion: 12,
            semanticVersion: '0.0.16',
            datasetName: '抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 2545,
            samplingValue: 2545,
          },
          {
            id: 6067,
            sampleId: 708,
            datasetId: 641,
            datasetVersionId: 6632,
            datasetVersion: 23,
            semanticVersion: '0.0.23',
            datasetName: '抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 2529,
            samplingValue: 2529,
          },
          {
            id: 6068,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5206,
            datasetVersion: 1,
            semanticVersion: '0.0.7',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 2471,
            samplingValue: 2471,
          },
          {
            id: 6069,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5207,
            datasetVersion: 2,
            semanticVersion: '0.0.5',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 1428,
            samplingValue: 1428,
          },
          {
            id: 6070,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5209,
            datasetVersion: 3,
            semanticVersion: '0.0.4',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 35,
            samplingValue: 35,
          },
          {
            id: 6071,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5210,
            datasetVersion: 4,
            semanticVersion: '0.0.3',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 108,
            samplingValue: 108,
          },
          {
            id: 6072,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5212,
            datasetVersion: 5,
            semanticVersion: '0.0.2',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 1343,
            samplingValue: 1343,
          },
          {
            id: 6073,
            sampleId: 708,
            datasetId: 665,
            datasetVersionId: 5213,
            datasetVersion: 6,
            semanticVersion: '0.0.1',
            datasetName: '数据部抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 686,
            samplingValue: 686,
          },
          {
            id: 6074,
            sampleId: 708,
            datasetId: 707,
            datasetVersionId: 5637,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '财务新体系附注表构成-公告抽取',
            datasetType: 'train',
            recordCount: 1124,
            samplingValue: 1124,
          },
          {
            id: 6075,
            sampleId: 708,
            datasetId: 708,
            datasetVersionId: 5639,
            datasetVersion: 1,
            semanticVersion: '0.0.2',
            datasetName: '财务新体系附注表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 801,
            samplingValue: 801,
          },
          {
            id: 6076,
            sampleId: 708,
            datasetId: 709,
            datasetVersionId: 5642,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 1881,
            samplingValue: 1881,
          },
          {
            id: 6077,
            sampleId: 708,
            datasetId: 710,
            datasetVersionId: 5644,
            datasetVersion: 1,
            semanticVersion: '0.0.5',
            datasetName: '财务新体系三大表定位-公告抽取',
            datasetType: 'train',
            recordCount: 1416,
            samplingValue: 1416,
          },
          {
            id: 6078,
            sampleId: 708,
            datasetId: 710,
            datasetVersionId: 5645,
            datasetVersion: 2,
            semanticVersion: '0.0.4',
            datasetName: '财务新体系三大表定位-公告抽取',
            datasetType: 'train',
            recordCount: 702,
            samplingValue: 702,
          },
          {
            id: 6079,
            sampleId: 708,
            datasetId: 710,
            datasetVersionId: 5647,
            datasetVersion: 3,
            semanticVersion: '0.0.2',
            datasetName: '财务新体系三大表定位-公告抽取',
            datasetType: 'train',
            recordCount: 3353,
            samplingValue: 3353,
          },
          {
            id: 6080,
            sampleId: 708,
            datasetId: 710,
            datasetVersionId: 5648,
            datasetVersion: 4,
            semanticVersion: '0.0.1',
            datasetName: '财务新体系三大表定位-公告抽取',
            datasetType: 'train',
            recordCount: 1734,
            samplingValue: 1734,
          },
          {
            id: 6081,
            sampleId: 708,
            datasetId: 712,
            datasetVersionId: 6062,
            datasetVersion: 2,
            semanticVersion: '0.0.1',
            datasetName: '财务新体系附注表定位-公告抽取',
            datasetType: 'train',
            recordCount: 1884,
            samplingValue: 1884,
          },
          {
            id: 6082,
            sampleId: 708,
            datasetId: 759,
            datasetVersionId: 6184,
            datasetVersion: 1,
            semanticVersion: '0.0.6',
            datasetName: '数据部财务新体系-补充科目',
            datasetType: 'train',
            recordCount: 1274,
            samplingValue: 1274,
          },
          {
            id: 6083,
            sampleId: 708,
            datasetId: 868,
            datasetVersionId: 6755,
            datasetVersion: 1,
            semanticVersion: '0.0.3',
            datasetName: '数据部公告抽取（被修改数据）',
            datasetType: 'train',
            recordCount: 135,
            samplingValue: 135,
          },
          {
            id: 6084,
            sampleId: 708,
            datasetId: 868,
            datasetVersionId: 6756,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '数据部公告抽取（被修改数据）',
            datasetType: 'train',
            recordCount: 553,
            samplingValue: 553,
          },
          {
            id: 6085,
            sampleId: 708,
            datasetId: 871,
            datasetVersionId: 6790,
            datasetVersion: 1,
            semanticVersion: '0.0.4',
            datasetName: '港股财务新体系附注表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 344,
            samplingValue: 344,
          },
          {
            id: 6086,
            sampleId: 708,
            datasetId: 872,
            datasetVersionId: 6771,
            datasetVersion: 1,
            semanticVersion: '0.0.4',
            datasetName: '港股财务新体系补充科目-公告抽取',
            datasetType: 'train',
            recordCount: 682,
            samplingValue: 682,
          },
          {
            id: 6087,
            sampleId: 708,
            datasetId: 873,
            datasetVersionId: 6778,
            datasetVersion: 1,
            semanticVersion: '0.0.3',
            datasetName: '越南财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 208,
            samplingValue: 208,
          },
          {
            id: 6088,
            sampleId: 708,
            datasetId: 873,
            datasetVersionId: 6779,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '越南财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6089,
            sampleId: 708,
            datasetId: 873,
            datasetVersionId: 6780,
            datasetVersion: 3,
            semanticVersion: '0.0.1',
            datasetName: '越南财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6090,
            sampleId: 708,
            datasetId: 874,
            datasetVersionId: 6782,
            datasetVersion: 1,
            semanticVersion: '0.0.3',
            datasetName: '越南财务新体系附注表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6091,
            sampleId: 708,
            datasetId: 874,
            datasetVersionId: 6784,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '越南财务新体系附注表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 204,
            samplingValue: 204,
          },
          {
            id: 6092,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 7714,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 1722,
            samplingValue: 1722,
          },
          {
            id: 6093,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 7913,
            datasetVersion: 3,
            semanticVersion: '0.0.3',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6094,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 7969,
            datasetVersion: 4,
            semanticVersion: '0.0.4',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6095,
            sampleId: 708,
            datasetId: 892,
            datasetVersionId: 6860,
            datasetVersion: 1,
            semanticVersion: '0.0.4',
            datasetName: '港股财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 612,
            samplingValue: 612,
          },
          {
            id: 6096,
            sampleId: 708,
            datasetId: 892,
            datasetVersionId: 8009,
            datasetVersion: 6,
            semanticVersion: '0.0.6',
            datasetName: '港股财务新体系三大表行分类-公告抽取',
            datasetType: 'train',
            recordCount: 1854,
            samplingValue: 1854,
          },
          {
            id: 6097,
            sampleId: 708,
            datasetId: 1409,
            datasetVersionId: 6846,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '数据部人工标注数据',
            datasetType: 'train',
            recordCount: 110,
            samplingValue: 110,
          },
          {
            id: 6098,
            sampleId: 708,
            datasetId: 1409,
            datasetVersionId: 7697,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '数据部人工标注数据',
            datasetType: 'train',
            recordCount: 103,
            samplingValue: 103,
          },
          {
            id: 6099,
            sampleId: 708,
            datasetId: 1437,
            datasetVersionId: 6926,
            datasetVersion: 2,
            semanticVersion: '0.0.2',
            datasetName: '港股财务新体系附注表定位-公告抽取',
            datasetType: 'train',
            recordCount: 726,
            samplingValue: 726,
          },
          {
            id: 6100,
            sampleId: 708,
            datasetId: 1439,
            datasetVersionId: 8012,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '越南财务新体系主表定位-公告抽取',
            datasetType: 'train',
            recordCount: 377,
            samplingValue: 377,
          },
          {
            id: 6101,
            sampleId: 708,
            datasetId: 1440,
            datasetVersionId: 6880,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '港股财务新体系主表定位-公告抽取',
            datasetType: 'train',
            recordCount: 2520,
            samplingValue: 2520,
          },
          {
            id: 6102,
            sampleId: 708,
            datasetId: 1478,
            datasetVersionId: 6872,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '港股财务新体系附注表构成-公告抽取',
            datasetType: 'train',
            recordCount: 629,
            samplingValue: 629,
          },
          {
            id: 6103,
            sampleId: 708,
            datasetId: 1483,
            datasetVersionId: 6874,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '港股财务新体系附注表转置-公告抽取',
            datasetType: 'train',
            recordCount: 600,
            samplingValue: 600,
          },
          {
            id: 6104,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 8314,
            datasetVersion: 7,
            semanticVersion: '0.0.7',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6105,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 8315,
            datasetVersion: 8,
            semanticVersion: '0.0.8',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6106,
            sampleId: 708,
            datasetId: 887,
            datasetVersionId: 8316,
            datasetVersion: 9,
            semanticVersion: '0.0.9',
            datasetName: '库表数据-公告抽取',
            datasetType: 'train',
            recordCount: 200,
            samplingValue: 200,
          },
          {
            id: 6107,
            sampleId: 708,
            datasetId: 641,
            datasetVersionId: 8239,
            datasetVersion: 25,
            semanticVersion: '0.1.1',
            datasetName: '抽取审核数据-公告抽取',
            datasetType: 'train',
            recordCount: 6153,
            samplingValue: 6153,
          },
          {
            id: 6108,
            sampleId: 708,
            datasetId: 1438,
            datasetVersionId: 8223,
            datasetVersion: 1,
            semanticVersion: '0.0.1',
            datasetName: '越南财务新体系附注表定位-公告抽取',
            datasetType: 'train',
            recordCount: 350,
            samplingValue: 350,
          },
          {
            id: 6109,
            sampleId: 708,
            datasetId: 1409,
            datasetVersionId: 8090,
            datasetVersion: 3,
            semanticVersion: '0.0.3',
            datasetName: '数据部人工标注数据',
            datasetType: 'train',
            recordCount: 25,
            samplingValue: 25,
          },
          {
            id: 6110,
            sampleId: 708,
            datasetId: 875,
            datasetVersionId: 8082,
            datasetVersion: 3,
            semanticVersion: '0.0.3',
            datasetName: '越南财务新体系补充科目-公告抽取',
            datasetType: 'train',
            recordCount: 407,
            samplingValue: 407,
          },
        ],
        mountPath: '/mnt/data2/',
        readOnly: true,
      },
    ],
    sumResource: {
      sumNodeCount: 1,
      sumCpuCount: 20,
      sumMemoryCount: 500,
      sumGpuCount: 8,
    },
    trainStoragePath: {
      id: 60648,
      storageId: 15,
      path: '/train/64/20128/workspace',
      subPath: '/train/64/20128/workspace',
    },
    shareInfo: [
      {
        id: 22282,
        trainId: 20128,
        shareStorageId: 23,
        shareStorageInfo: {
          id: 23,
          createTime: '2024-09-03 02:59:32',
          updateTime: '2024-09-03 16:10:36',
          name: '弗吉尼亚二-人工智能-共享存储',
          tenantId: 14,
          proCode: '793',
          mountPath: '/mnt/data/',
          storagePathId: 3484,
          clusterCode: 'csva2ai',
          quota: 1073741824,
          description: '弗吉尼亚二-人工智能-共享存储',
          creator: null,
          tenantName: 'iwc',
          proName: '代码生成',
          storageId: 15,
          filepath: '/sharestorage/iwc/share',
          quotaShow: '1 GB',
          usedShow: null,
          creatorName: null,
        },
        mountPath: '/mnt/data/',
        envVar: '',
      },
    ],
    advancedSetting: {
      exposeMetrics: null,
    },
    fileInfo: [
      {
        path: '/data/config/config.yaml',
        content:
          'description: "sft:qwen7b 2.5 增加越南训练数据"\nmodelVersion: "V149"\nminorVersion: "dsExtractSft_qwen7bV149V3.0"\nmodelId: \'64\'\nmodelName:  hithink-event-extraction\n\nvar:\n  workspace: "/data/workspace/cjy/project/llm-nlu"\n  baseModeDir: "/mnt/data/model/chat/Qwen2.5-7B-Instruct"\n  saveDir: "/mnt/data/kg/runs/20250411/7b-qwen2.5-extraction-V149"\n  dataConfigPath: "/etc/datasetsGroupConfigs/AIMELlm/config.json"\n  trData: "/mnt/data/kg/线上数据处理/dataset/train/trainV149.jsonl"\n  \npipeline:\n\n\n\n  - SFT训练:\n    - module: trainSft\n      modelNameOrPath: "$baseModeDir"\n      dataPath: "$trData"\n      numTrainEpochs: 3\n      outputDir: "$saveDir"\n      perDeviceTrainBatchSize: 1\n      gradientAccumulationSteps: 48\n      evaluationStrategy: "no"\n      saveStrategy: "steps"\n      saveSteps: 50000\n      saveTotalLimit: 1\n      learningRate: 2e-5\n      weightDecay: 0.0\n      warmupRatio: 0.03\n      lrSchedulerType: "cosine"\n      loggingSteps: 1\n      tf32: True\n      gradientCheckpointing: True\n      dataloaderNum_workers: 1\n      modelMaxLength: 32000\n      deepspeed: dsConfig_z3.json\n      reportTo: none\n      prompt: chatTemplate\n      filterByLength: True\n      bf16: True\n\n\n  - 模型效果评估:\n    - module: eval\n      config: "/mnt/data/kg/llm-nlu/llm-eval/config/configExt.yaml"\n      modelId: \'64\'\n      \n      modelPath: $saveDir\n      modelName:  hithink-event-extraction      \n      # 数据部抽取评测\n      saveDir: $saveDir/evalPredictOpenai\n      # where to save your prediect result (currently support Hithink llama3 none qwen)\n      promptType: chatTemplate\n      \n      # 评估结果上传人\n      submiter: guoxinrun@myhexin.com\n      maxSeqLength: 16820\n\n      tensorParallel: 1\n      tasks:\n\n          抽取审核数据-公告抽取:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__抽取审核数据-公告抽取__0-0-4.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/evalExtract_json.py\n\n          数据部16个抽取业务-zero-shot:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__数据部16个抽取业务-zero-shot__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/evalExtract_json.py\n\n          财务新体系_三大表定位:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__财务新体系三大表定位-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/extract_jsonEvalPosition.py\n\n          财务新体系_附注表定位:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__财务新体系附注表定位-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/noteTablePositionEval.py\n\n          财务新体系_附注表构成:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__财务新体系附注表构成-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/tableConstructEval.py\n\n          财务新体系_利润表行分类:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__财务新体系三大表行分类-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/tableRowEval.py\n\n          财务新体系_利润表附注行分类:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__财务新体系附注表行分类-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/noteTableRowEval.py\n\n          库表数据-公告抽取:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__库表数据-公告抽取__0-0-1.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/evalExtract_json.py\n\n          数据部抽取审核数据-公告抽取:\n              type: text\n              dataPath: /sft/data/TESTSET/TESTSET__数据部抽取审核数据-公告抽取__0-0-4.jsonl\n              compareFunc:\n                  path:  /mnt/data/kg/llm-eval/utils/evalExtract_json.py\n            \n            ',
      },
    ],
  },
  clusterInfo: {
    clusterCode: 'csva2ai',
    alias: '弗吉尼亚二-人工智能',
    executorType: 2,
    resourcePools: null,
    selfBuild: 1,
    storageId: 15,
  },
  resourcePoolInfo: null,
  frameworkInfo: {
    name: 'PyTorchJob',
    nodeTypes: ['worker'],
  },
  executorDetail: {},
  train_workspace: {
    id: 60648,
    storageId: 15,
    path: '/train/64/20128/workspace',
    subPath: '/train/64/20128/workspace',
  },
};
