/*
 * @creater: panan
 * @message: mock
 * @since: 2024-08-29 17:00:35
 * @LastAuthor: panan panan2001@outlook.com
 * @lastTime: 2024-08-31 14:17:58
 * @文件相对于项目的路径: /pan-umi/src/pages/NetworkTopologyDiagram/mock.tsx
 */
export const data = {
    "nodes": [
        {
            "type": "warnningHost",
            "id": "h1",
            "properties": {
                "name": "csva2ait-k8snode-test"
            }
        },
        {
            "type": "errorHost",
            "id": "h2",
            "properties": {
                "name": "csv-de-wulancabu"
            }
        },
        {
            "type": "normalHost",
            "id": "1",
            "properties": {
                "name": "csva2ait-k8snode-72-43"
            }
        },
        {
            "type": "normalHost",
            "id": "2",
            "properties": {
                "name": "csva2ait-k8snode-72-44"
            }
        },
        {
            "type": "normalSwitch",
            "id": "3",
            "properties": {
                "name": "SW1-400G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        },
        {
            "type": "normalSwitch",
            "id": "4",
            "properties": {
                "name": "SW2-400G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        },
        {
            "type": "normalSwitch",
            "id": "5",
            "properties": {
                "name": "SW3-10G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        },
        {
            "type": "normalSwitch",
            "id": "6",
            "properties": {
                "name": "SW4-10G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        },
        {
            "type": "normalSwitch",
            "id": "7",
            "properties": {
                "name": "SW5-10G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        },
        {
            "type": "normalSwitch",
            "id": "8",
            "properties": {
                "name": "SW6-10G",
                "cpu": "59",
                "memory": "10",
                "temp": "30",
                "fan": "normal",
                "power": "normal",
                "abnormal": []
            }
        }
    ],
    "edges": [
        {
            "id": "e1",
            "type": "warnning",
            "source": "1",
            "target": "3",
            "properties": {
                "data": [
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/5",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens108",
                        "type": "warnning",
                        "gpu": "0",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": ["SW1-400G FourHundredGigE1/0/5 丢包数:3", "csva2ait-k8snode-72-43 ens108 乱序报数: 10"]
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/6",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens109",
                        "type": "normal",
                        "gpu": "1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/7",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens110",
                        "type": "normal",
                        "gpu": "2",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/8",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens111",
                        "type": "normal",
                        "gpu": "3",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e2",
            "type": "normal",
            "source": "1",
            "target": "4",
            "properties": {
                "data": [
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/5",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens112",
                        "type": "normal",
                        "gpu": "4",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/6",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens113",
                        "type": "normal",
                        "gpu": "5",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/7",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens114",
                        "type": "normal",
                        "gpu": "6",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/8",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens115",
                        "type": "normal",
                        "gpu": "7",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "storage",
                        "ifname": "FourHundredGigE1/0/18",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens12",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e3",
            "type": "normal",
            "source": "1",
            "target": "6",
            "properties": {
                "data": [
                    {
                        "switchName": "SW4-10G",
                        "netType": "paas",
                        "ifname": "Ten-GigabitEthernet1/0/1",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens20f0",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW4-10G",
                        "netType": "paas",
                        "ifname": "Ten-GigabitEthernet1/0/2",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens20f1",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e4",
            "type": "normal",
            "source": "2",
            "target": "3",
            "properties": {
                "data": [
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/1",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens108",
                        "type": "normal",
                        "gpu": "0",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/2",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens109",
                        "type": "normal",
                        "gpu": "1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/3",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens110",
                        "type": "normal",
                        "gpu": "2",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW1-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/4",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens111",
                        "type": "normal",
                        "gpu": "3",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e5",
            "type": "normal",
            "source": "2",
            "target": "3",
            "properties": {
                "data": [
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/1",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens112",
                        "type": "normal",
                        "gpu": "4",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/2",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens113",
                        "type": "normal",
                        "gpu": "5",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/3",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens114",
                        "type": "normal",
                        "gpu": "6",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "compute",
                        "ifname": "FourHundredGigE1/0/4",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens115",
                        "type": "normal",
                        "gpu": "7",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW2-400G",
                        "netType": "storage",
                        "ifname": "FourHundredGigE1/0/17",
                        "actualbandwidth": "400Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens12",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e6",
            "type": "normal",
            "source": "2",
            "target": "5",
            "properties": {
                "data": [
                    {
                        "switchName": "SW3-10G",
                        "netType": "paas",
                        "ifname": "Ten-GigabitEthernet1/0/1",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens20f0",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    },
                    {
                        "switchName": "SW3-10G",
                        "netType": "paas",
                        "ifname": "Ten-GigabitEthernet1/0/2",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens20f1",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e7",
            "type": "normal",
            "source": "1",
            "target": "7",
            "properties": {
                "data": [
                    {
                        "switchName": "SW5-10G",
                        "netType": "outband",
                        "ifname": "Ten-GigabitEthernet1/0/1",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-43",
                        "hca": "ens120",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        {
            "id": "e8",
            "type": "normal",
            "source": "2",
            "target": "8",
            "properties": {
                "data": [
                    {
                        "switchName": "SW6-10G",
                        "netType": "outband",
                        "ifname": "Ten-GigabitEthernet1/0/1",
                        "actualbandwidth": "10Gb/s",
                        "serverName": "csva2ait-k8snode-72-44",
                        "hca": "ens120",
                        "type": "normal",
                        "gpu": "-1",
                        "server": {
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "switch": {
                            "InBytes": "1024",
                            "OutBytes": "1024",
                            "InPkts": "4096090",
                            "OutPkts": "4096090",
                            "InDiscard": "0",
                            "OutDiscard": "0",
                            "InErrors": "0",
                            "OutErrors": "0",
                            "InBPS": "178Gb/s",
                            "OutBPS": "178Gb/s",
                            "InPPS": "0 p/s",
                            "OutPPS": "0 p/s",
                            "InDisPS": "0 p/s",
                            "OutDisPS": "0 p/s",
                            "InErrPS": "0 p/s",
                            "OutErrPS": "0 p/s",
                            "portStatus": "UP",
                            "optStatus": "UP",

                            "optRXPower": "2.56dBm",
                            "optTXPower": "2.56dBm",
                            "optTemp": "35℃",
                            "optVol": "35v",
                            "optBias": "8.91mA"
                        },
                        "abnormal": []
                    }
                ]
            }
        },
        // {
        //     "id": "eh1",
        //     "type": "warnning",
        //     "source": "h1",
        //     "target": "3",
        //     "properties": {
        //         "data": [
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/5",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens108",
        //                 "type": "warnning",
        //                 "gpu": "0",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": ["SW1-400G FourHundredGigE1/0/5 丢包数:3", "csva2ait-k8snode-72-43 ens108 乱序报数: 10"]
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/6",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens109",
        //                 "type": "normal",
        //                 "gpu": "1",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/7",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens110",
        //                 "type": "normal",
        //                 "gpu": "2",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/8",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens111",
        //                 "type": "normal",
        //                 "gpu": "3",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             }
        //         ]
        //     }
        // },
        // {
        //     "id": "eh2",
        //     "type": "warnning",
        //     "source": "h2",
        //     "target": "4",
        //     "properties": {
        //         "data": [
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/5",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens108",
        //                 "type": "warnning",
        //                 "gpu": "0",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": ["SW1-400G FourHundredGigE1/0/5 丢包数:3", "csva2ait-k8snode-72-43 ens108 乱序报数: 10"]
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/6",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens109",
        //                 "type": "normal",
        //                 "gpu": "1",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/7",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens110",
        //                 "type": "normal",
        //                 "gpu": "2",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             },
        //             {
        //                 "switchName": "SW1-400G",
        //                 "netType": "compute",
        //                 "ifname": "FourHundredGigE1/0/8",
        //                 "actualbandwidth": "400Gb/s",
        //                 "serverName": "csva2ait-k8snode-72-43",
        //                 "hca": "ens111",
        //                 "type": "normal",
        //                 "gpu": "3",
        //                 "server": {
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "switch": {
        //                     "InBytes": "1024",
        //                     "OutBytes": "1024",
        //                     "InPkts": "4096090",
        //                     "OutPkts": "4096090",
        //                     "InDiscard": "0",
        //                     "OutDiscard": "0",
        //                     "InErrors": "0",
        //                     "OutErrors": "0",
        //                     "InBPS": "178Gb/s",
        //                     "OutBPS": "178Gb/s",
        //                     "InPPS": "0 p/s",
        //                     "OutPPS": "0 p/s",
        //                     "InDisPS": "0 p/s",
        //                     "OutDisPS": "0 p/s",
        //                     "InErrPS": "0 p/s",
        //                     "OutErrPS": "0 p/s",
        //                     "portStatus": "UP",
        //                     "optStatus": "UP",

        //                     "optRXPower": "2.56dBm",
        //                     "optTXPower": "2.56dBm",
        //                     "optTemp": "35℃",
        //                     "optVol": "35v",
        //                     "optBias": "8.91mA"
        //                 },
        //                 "abnormal": []
        //             }
        //         ]
        //     }
        // },
    ],
}